### ISSUE TITLE
please make LICENCE

### ISSUE THREAD

**Issue by biohuns** [kotarot/chample#3]
@kotarot 
I want to use this library on my code. (I'm making golang wrapper of this library.)
Please specify the licence of this library if you are OK.

I am very grateful that you made this library.

**Comment by kotarot** [comment]
@biohuns Thank you for being interested in this repository!

Sure! LICENSE is definitely needed. I'll add it tonight or tomorrow. Please be patient for a little while.

**Comment by kotarot** [comment]
@biohuns Hi, I just added the license: https://github.com/kotarot/chample/pull/4

**Comment by biohuns** [comment]
@kotarot  Thank you! I will use it. very helpful.
